#!/bin/bash

DIR=/home/sadmin
exec &> $DIR/logs/summaries/$(date +%Y%m%d)_summary.txt


# --- get all block devices
DISKS=()
while IFS= read -r line; do
    DISKS+=( "$line" )
done < <( lsblk -d | cut -d" " -f1 |grep -e '^s' )

# --- get all pools
POOLS=()
while IFS= read -r line; do
    POOLS+=( "$line" )
done < <( /sbin/zfs list -H -d 0 | cut -f1 )

# --- start SMART short test for all drives and then wait for 5 min
for i in "${DISKS[@]}"; do
    /usr/sbin/smartctl -q silent -t short /dev/$i
done
sleep 5m

# --- print out zpool health, capacity and disk temperatures
echo ""
echo "SUMMARY - $(date +%d.%m.%Y):"
echo ""
for i in "${POOLS[@]}"; do
    echo "$i"
    echo -e "Health:\t$(/sbin/zpool get -H health $i | cut -f3)"
    echo -e "Usage:\t$(/sbin/zpool get -H capacity $i | cut -f3)"
    echo -e "Frag:\t$(/sbin/zpool get -H fragmentation $i | cut -f3)"
done
echo ""
for i in "${DISKS[@]}"; do
    TEMP=$(/usr/sbin/hddtemp -n /dev/$i)
    BAD_SECTORS=$(/usr/sbin/smartctl -f brief  -a /dev/$i | grep "Current_Pending_Sector" | sed 's/ \+ /\t/g' |cut -f7)
    if [[ ! -z "$BAD_SECTORS" ]]; then
        echo "/dev/$i: $TEMP°C and $BAD_SECTORS cps"
    else
        echo "/dev/$i: $TEMP°C"
    fi
done
echo ""
# --- send summary via mail 
echo "<pre>$(cat $DIR/logs/summaries/$(date +%Y%m%d)_summary.txt)</pre>" | mail -a "From: PPE Storage <messages@ppe.live>" -a "Content-type: text/html" -s "PPE Storage - Weekly summary" pbuchinger@protonmail.ch

