#!/bin/bash

# check pool health and hdd temperatures

DIR=/home/sadmin
exec &> $DIR/logs/warnings/$(date +%Y%m%d-%H:%M)_warning.log

# --- global vars
MAX_TEMP=50
WARNING=false

# --- get all block devices
DISKS=()
while IFS= read -r line; do
    DISKS+=( "$line" )
done < <( lsblk -d | cut -d" " -f1 |grep -e '^s' )

# --- get all pools
POOLS=()
while IFS= read -r line; do
    POOLS+=( "$line" )
done < <( /sbin/zfs list -H -d 0 | cut -f1 )

# --- check zpool health
echo ""
for i in "${POOLS[@]}"; do
    STATE=$(/sbin/zpool get -H health $i | cut -f3)
    if [[ "$STATE" != "ONLINE" ]]; then
        echo "ATTENTION: $i is in an abnormal state: $STATE"
        WARNING=true
    fi
done

#--- check hdd temps
echo ""
for i in "${DISKS[@]}"; do
    CURR_TEMP=$(/usr/sbin/hddtemp -n /dev/$i)
    if [[ "$CURR_TEMP" -gt "$MAX_TEMP" ]]; then
        echo "ATTENTION: Disk /dev/$i reached $CURR_TEMP°C."
        WARNING=true
    fi
done

if [[ "$WARNING" == "true" ]]; then
    # --- send summary via mail
    echo "<pre>$(cat $DIR/logs/warnings/$(date +%Y%m%d-%H:%M)_warning.log)</pre>" | mail -a "From:" -a "Content-type: text/html" -s ""
else
    # --- delete empty warning log
    rm -f $DIR/logs/warnings/$(date +%Y%m%d-%H:%M)_warning.log
fi
